name: deploy-to-prod

on:
  workflow_run:
    workflows: ["CI"]   # <-- aquí debe coincidir con el "name:" que tengas en ci.yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to PROD..."
          date
